# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

workspace '../../Gist.xcworkspace'

target 'Presentation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  project 'Presentation.xcodeproj'

  pod 'Device', '~> 3.2.1'
  pod 'PaginatedTableView'
  pod 'StatefulViewController', '~> 3.0'

  target 'PresentationTests' do
    inherit! :search_paths
  end

end
